"""
Django settings for ivelum project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

SECRET_KEY = 'django-insecure-#-du&(^lfzv$y=v3=y!s4=pmm-po&u8-9)f&6z9pdpqzjkdy&n'

ROOT_URLCONF = 'ivelum.urls'

BASE_DIR = Path(__file__).resolve().parent.parent

WSGI_APPLICATION = 'ivelum.wsgi.application'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEBUG = True
